const fifty = [
    `Mathematics, a universal language, unveils the beauty of patterns and logic. Pythagoras's theorem, for instance, relates the sides of a right triangle: a squared plus b squared equals c squared. This simple equation underpins geometry, enabling us to measure and understand the world's countless right-angled wonders. Maths is the key to unlocking nature's secrets.`,
    `Mathematics is a timeless art, where numbers dance with equations. The Fibonacci sequence, 0, 1, 1, 2, 3, 5, 8, 13, and so on, reveals nature's hidden patterns. It's the secret code behind spirals in seashells, the arrangement of petals, and even the stock market's fluctuations. In math, beauty abounds.`,
    `Mathematics, the language of the universe, unveils order in chaos. It's a symphony of numbers, equations, and patterns that bridge the real and abstract worlds. From ancient geometry to modern calculus, math guides us in understanding the fundamental laws that govern our universe, unlocking its mysteries.`,
    `In the depths of space, black holes are cosmic enigmas. These gravitational behemoths warp spacetime, trapping everything, even light. As mysterious as they are, they offer profound insights into the fabric of the universe. Scientists continue to study them, uncovering the secrets of these celestial giants.`,
    `Within our cells, DNA is the keeper of life's blueprint. Its double helix structure, like a molecular ladder, encodes genetic instructions that shape every living organism. From the tiniest bacterium to the mightiest redwood tree, DNA unites all of life, reminding us of our shared origins and interconnectedness.`,
    `In the heart of the atom, the nucleus holds the key to matter's mysteries. Protons and neutrons cluster within, bound by the strong nuclear force. Despite its small size, the nucleus determines an element's identity and stability, offering a glimpse into the powerful forces that govern the subatomic realm.`,
    `In the world of quantum mechanics, particles defy our intuition. They can exist in multiple states at once and become entangled across vast distances, as if sharing a secret conversation. It's a realm where reality behaves unlike anything we experience, challenging our understanding of the fundamental nature of the universe.`,
    `In the digital realm, algorithms are the unsung heroes. They power search engines, recommend content, and secure our data. From simple sorting to complex machine learning, algorithms are the brains behind the screens, shaping the way we interact with technology. Computer scientists continue to innovate, pushing the boundaries of what's possible.`,
    `Alan Turing, a visionary mathematician and computer scientist, played a pivotal role in World War II. His code-breaking genius cracked the Enigma machine, unraveling Nazi secrets and aiding the Allies' victory. Turing's legacy extends beyond wartime heroics; he laid the groundwork for modern computing and artificial intelligence, shaping the digital age.`,
    `C.V. Raman, a brilliant Indian physicist, discovered the Raman Effect in 1928, which revolutionized our understanding of light scattering. His groundbreaking work earned him the Nobel Prize in Physics in 1930, making him the first Indian scientist to receive this prestigious honor. Raman's legacy continues to inspire generations of scientists.`,
    `Rabindranath Tagore, a multifaceted Indian polymath, reshaped literature and the arts. In 1913, he became the first non-European to win the Nobel Prize in Literature for his collection of poems, Gitanjali. Beyond his prolific writing, Tagore's philosophies of universalism and humanism continue to inspire creativity and cultural exchange worldwide.`,
    `Dr. A.P.J. Abdul Kalam, renowned as the 'Missile Man of India,' spearheaded India's space and missile programs. As the 11th President of India, he remained a visionary scientist, inspiring millions with his dedication to science and education. His legacy continues to motivate young minds to reach for the stars.`,
    `Swami Vivekananda, a disciple of Sri Ramakrishna, introduced Indian philosophy and spirituality to the Western world in 1893. His iconic speech at the Parliament of the World's Religions in Chicago awakened the world to the richness of Indian wisdom. His teachings of universal spirituality continue to inspire seekers worldwide.`,
];

const seventyfive = [
    `Subhas Chandra Bose, affectionately known as Netaji, was a prominent Indian nationalist leader in the early 20th century. His unwavering commitment to India's independence from British colonial rule made him an iconic figure in the struggle for freedom. Netaji's famous rallying cry, 'Give me blood, and I shall give you freedom,' inspired countless Indians to join the fight for independence. His leadership and role in founding the Indian National Army (INA) are celebrated for their significant contributions to India's journey to sovereignty. Netaji's legacy endures as a symbol of patriotism and courage in Indian history.`,
    `Climate change, driven by human activities like burning fossil fuels and deforestation, poses a severe global threat. Rising temperatures, extreme weather events, and sea-level rise are already impacting communities and ecosystems worldwide. Urgent action, including reducing greenhouse gas emissions, transitioning to clean energy sources, and adopting sustainable practices, is imperative. Climate change is not just an environmental issue; it's a social, economic, and humanitarian challenge that requires a concerted global effort to mitigate its effects and safeguard our planet for future generations.`,
    `The Mughal Empire, which flourished in the Indian subcontinent from the early 16th to the mid-19th century, was a remarkable dynasty known for its cultural, architectural, and artistic achievements. Under emperors like Akbar, Shah Jahan, and Aurangzeb, the Mughals constructed magnificent monuments like the Taj Mahal and promoted a rich blend of Persian and Indian cultures. However, their rule also saw political intrigues and conflicts. The Mughal Empire left an enduring legacy in India's history, shaping its art, architecture, and cultural diversity.`,
    `India's rich history spans millennia, encompassing ancient civilizations, empires, and profound cultural contributions. The Indus Valley Civilization, dating back to 2500 BCE, showcases advanced urban planning. The Maurya and Gupta Empires marked periods of great intellectual and artistic achievements. The Mughal Empire's architectural wonders, like the Taj Mahal, remain iconic. British colonial rule followed, leading to India's struggle for independence, finally achieved in 1947. India's history is a tapestry of diverse cultures, traditions, and events, shaping its vibrant identity.`,
    `Mahatma Gandhi, a towering figure in India's struggle for independence, advocated nonviolent civil disobedience as a potent weapon against British colonial rule. His leadership in movements like the Salt March and Quit India made a profound impact. Gandhi's principles of truth, nonviolence, and social justice inspired not only India but also civil rights leaders worldwide. His unwavering commitment to justice and equality remains a beacon of hope and a testament to the power of peaceful resistance in the face of oppression.`,
    `Indian independence, achieved on August 15, 1947, marked a historic milestone in the nation's struggle for freedom. After years of nonviolent resistance led by figures like Mahatma Gandhi and Jawaharlal Nehru, India gained sovereignty from British colonial rule. This momentous event, celebrated annually as Independence Day, signified the end of foreign domination and the beginning of a new era of self-governance. It remains a source of immense pride for the nation, symbolizing the triumph of determination and unity in the pursuit of liberty.`,
    `Indian business, a dynamic force in the global economy, is characterized by diversity and innovation. From traditional family-run enterprises to cutting-edge tech startups, India's business landscape spans a wide spectrum. Industries like IT, pharmaceuticals, and manufacturing have flourished, attracting international investment. Government initiatives such as 'Make in India' aim to boost manufacturing, while digital transformations are propelling e-commerce and fintech. With a large and youthful workforce, India's business potential remains a powerful driver of economic growth and innovation on the world stage.`,
    `Sports in India have a rich and diverse history, with cricket, field hockey, and kabaddi being among the most popular. Cricket, in particular, has attained almost a religious status in the country, with passionate fans and world-class players. Field hockey, once India's national sport, has a storied Olympic history. In recent years, there's been a growing interest in other sports like badminton, wrestling, and athletics, with Indian athletes making their mark on the international stage, showcasing the nation's sporting potential.`,
    `The Indian Space Research Organisation (ISRO) is India's premier space agency, founded in 1969. Over the decades, ISRO has achieved remarkable milestones in space exploration. Notable successes include launching missions to the Moon (Chandrayaan-1 and Chandrayaan-2) and Mars (Mangalyaan). ISRO's cost-effective and innovative approach to space technology has earned it global recognition. It continues to work on a variety of missions, from satellite launches to interplanetary exploration, playing a vital role in advancing India's scientific and technological capabilities in space.`,
    `The Indian Army, one of the world's largest military forces, stands as the guardian of India's territorial integrity and national security. Established in 1947 following India's independence, it has a rich legacy of valor and sacrifice. Committed to defending the nation from external threats and providing aid during disasters, the Indian Army embodies discipline, courage, and dedication. Its diverse and highly skilled personnel are ever-ready to protect the nation's interests, making it an integral part of India's strength and resilience.`,
    `The stock market is a dynamic financial marketplace where buyers and sellers trade shares of publicly-listed companies. It serves as a barometer of economic health and investor sentiment. Prices fluctuate based on various factors, including company performance, economic indicators, and global events. Investors seek opportunities for capital growth and income through stock ownership. While it offers the potential for substantial returns, it also carries risks. Successful stock market participation often requires research, analysis, and a long-term perspective to navigate the complexities of this financial arena.`,
    `World War II, spanning from 1939 to 1945, was a global conflict that reshaped the course of history. Triggered by the invasion of Poland by Nazi Germany, it engulfed nations across Europe, Asia, and beyond. The war saw the rise of totalitarian regimes, atrocities like the Holocaust, and major battles like D-Day. It ended with the dropping of atomic bombs on Hiroshima and Nagasaki, leading to Japan's surrender. World War II's legacy includes the founding of the United Nations and lessons in the pursuit of peace and cooperation.`,
];

const hundred = [
    `Health care is experiencing a wave of innovation driven by technology. Telemedicine, wearable health devices, and electronic health records have enhanced patient care and made health information more accessible. Advances in genomics and personalized medicine are enabling tailored treatments based on an individual's genetic makeup. Artificial intelligence is revolutionizing diagnostics and drug discovery, potentially improving patient outcomes. However, these innovations also raise ethical and privacy concerns. The COVID-19 pandemic accelerated the adoption of telehealth, highlighting its potential for providing remote care. The ongoing challenge is to harness these innovations to create a more efficient, equitable, and patient-centered health care system.`,
    `The digital age has transformed education, making knowledge accessible to more people than ever before. Online learning platforms, virtual classrooms, and e-books have expanded educational opportunities, especially in remote or underserved areas. However, this shift also poses challenges, such as the digital divide and concerns about the quality of online education. The COVID-19 pandemic accelerated the adoption of digital learning, highlighting the need for effective online teaching methods and equitable access to technology. As education continues to evolve, striking a balance between traditional and digital approaches is essential to ensure inclusive and effective learning experiences.`,
    `In recent years, technology has advanced at an astonishing pace, revolutionizing how we live and work. The rapid development of smartphones, artificial intelligence, and the Internet of Things (IoT) has transformed the way we communicate, shop, and even travel. With the advent of 5G networks, our connectivity has become faster and more reliable, opening up new possibilities in areas like remote work and autonomous vehicles. However, as technology continues to evolve, concerns about privacy, cybersecurity, and its impact on employment are also gaining prominence, highlighting the need for responsible innovation.`,
    `As the global population continues to grow, ensuring food security while minimizing environmental impact is a paramount challenge. Sustainable agriculture practices are gaining prominence, emphasizing responsible land use, reduced chemical inputs, and conservation of biodiversity. Precision farming technologies, including drones and sensors, are optimizing crop yields while minimizing resource use. Additionally, alternative food sources like plant-based proteins and lab-grown meats are emerging as environmentally friendly alternatives to traditional livestock farming. Sustainable agriculture not only addresses food security but also plays a critical role in mitigating climate change and preserving the Earth's ecosystems.`,
    `Space exploration is entering an exciting era with ambitions to send humans to Mars and beyond. Initiatives by both government agencies and private companies are pushing the boundaries of space travel. SpaceX's Starship and NASA's Artemis program are key players in lunar exploration, while SpaceX's Mars colonization plans envision a future where humans become a multi-planetary species. However, the challenges are immense, including radiation exposure, life support systems, and the sustainability of off-world colonies. Space exploration holds promise for scientific discovery and resource utilization but also raises ethical questions about preserving celestial environments and ensuring equitable access to space opportunities.`,
    `The world is experiencing rapid urbanization, with more people moving to cities in search of better opportunities. This trend has led to the emergence of megacities—urban areas with populations exceeding ten million. Megacities like Tokyo, Mumbai, and New York face unique challenges such as congestion, pollution, and housing shortages. Urban planners are increasingly focusing on sustainable city design, including efficient public transportation systems, green spaces, and smart technologies to improve quality of life. Balancing economic growth with environmental sustainability is crucial in managing the urbanization trend and ensuring that megacities remain vibrant and livable.`,
    `The nature of work is evolving rapidly, driven by automation, artificial intelligence, and the gig economy. Traditional employment models are giving way to flexible work arrangements, remote work, and freelancing. While these changes offer greater flexibility and opportunities, they also raise questions about job security, worker rights, and income inequality. Upskilling and adaptability have become essential in this dynamic job market. Employers are exploring innovative ways to support their workforce, such as reskilling programs and a focus on employee well-being. The future of work will likely be characterized by a blend of human and machine collaboration, requiring continuous learning and adaptability.`,
    `The proliferation of artificial intelligence (AI) and machine learning (ML) technologies brings forth a crucial discussion on ethics. AI systems are increasingly integrated into our daily lives, influencing decision-making processes in areas like healthcare, finance, and law enforcement. Concerns about bias, transparency, and accountability have arisen as AI algorithms make high-stakes decisions. Ethical considerations include ensuring fairness, privacy protection, and adherence to human values. As AI continues to advance, fostering ethical AI development and governance is imperative. Collaboration between technologists, policymakers, and ethicists is essential to strike a balance between innovation and ethical principles.`,
    `The COVID-19 pandemic underscored the importance of global health preparedness and cooperation. It revealed vulnerabilities in healthcare systems, supply chains, and the need for rapid vaccine development. The pandemic prompted discussions on strengthening international health organizations and early warning systems. While vaccines and treatments have been developed at record speed, equitable access remains a challenge. The crisis also highlighted the crucial role of public health measures and community engagement in controlling infectious diseases. Lessons learned from the pandemic are shaping future pandemic preparedness efforts, emphasizing the need for resilient healthcare systems and global collaboration to address emerging health threats.`,
    `In an increasingly digital world, cybersecurity is a paramount concern. Cyberattacks are becoming more sophisticated and prevalent, targeting individuals, businesses, and governments. Threats like ransomware, data breaches, and phishing attacks pose significant risks to data privacy and national security. The demand for cybersecurity experts is growing as organizations invest in protecting their digital assets. Addressing these challenges requires robust cybersecurity strategies, user awareness, and international cooperation to combat cybercrime. As technology continues to advance, staying ahead of cyber threats remains an ongoing and critical endeavor.`,
    `The transportation sector is a significant contributor to greenhouse gas emissions. Transitioning to renewable and sustainable transportation is a critical step in mitigating climate change. Electric vehicles (EVs) powered by clean energy sources are gaining popularity, with advancements in battery technology increasing their range and affordability. Public transportation systems are also shifting toward electrification. Initiatives to promote cycling and walking are reducing the reliance on fossil fuel-powered vehicles. To accelerate this transition, investment in charging infrastructure, green public transit options, and policies that incentivize eco-friendly transportation choices are essential.`,
    `Artificial intelligence (AI) is revolutionizing healthcare. AI-driven applications, such as diagnostic algorithms and predictive analytics, have the potential to enhance patient care, streamline processes, and improve outcomes. Machine learning models can analyze vast datasets to identify trends and assist in early disease detection. Telemedicine platforms are integrating AI for remote patient monitoring and personalized treatment recommendations. However, ensuring the ethical use of AI in healthcare, data security, and regulatory compliance are key concerns. The synergy of medical expertise and AI capabilities holds great promise for the future of healthcare, offering more accessible, efficient, and accurate medical service`,
];

const hundredfifty = [
    `Obesity rates in school-aged children continue growing and influencing their development. In addition to personal concerns and social judgments, overweight and obese children are at risk for long-term health consequences, including cardiovascular problems, metabolic changes, and additional comorbidities (Karp & Gessell, 2015). Today, it is not enough to recognize and control this problem. It is high time for schools to think about the interventions they choose to protect children and remove as many obesity-related factors as possible. Healthy food like salads and fish should replace fast food, and fresh juices and water must be offered instead of soda or Coca-Cola.In addition to healthy eating, physical activities and education are to be promoted. Many children remain unaware of how to protect their health and avoid obesity, so the task of schools is to increase awareness and contribute to healthy lifestyles.Obesity is not a disease anymore but a social burden.`,
    `The points on the poliovirus’s causes, manifestations, and outcomes presented in the discussion post are thorough and
    informative. To add to the discussion, it is relevant to address additional causes of poliovirus outbreaks to advance prevention
    approaches. Indeed, according to Georgieva et al. (2020), laboratory workers and medical staff working with infected
    populations might transmit the virus, which justifies the obligatory vaccination of this group for patient safety. Moreover, the
    type of vaccination used for poliovirus plays a significant role in its effectiveness. In particular, the oral poliovirus vaccine deems
    insufficiently effective when used once due to the outbreak of multiple new poliovirus cases after obtaining the oral vaccine
    (Duintjer Tebbens & Thompson, 2018). The severity of the disease and the lack of universally effective treatment measures and
    preventative practices make it one of the world’s emergencies today. For that matter, research in the field of polio vaccination is
    required`,
    `The primary types of alternative dispute resolution (ADR) methods include mediation and arbitration. Mediation involves the use
    of a mediator to reach a settlement between conflicting parties. The process has no formality, and both parties have to agree to
    the settlement to make it binding to them, while the mediator only facilitates the process (Winataa and Adityab 92). Unlike
    mediation, arbitration is a legal process, and the arbitrator selects a settlement which is binding to both parties. Chris Tycol
    should use arbitration as a legally binding process and is more enforceable than mediation (Zeller and Trakman 453). While
    mediation and arbitration are the primary ADR methods, others include conciliation and negotiation. Tycol’s case is classified as
    probate because it involves wills and estates. Therefore, it should be heard by a state court, which hears criminal and probate
    cases, among others. However, Tycol can appeal with the US Supreme Court, which decides whether to hear an appeal or not.
    `,
    `Social media and social networking are relatively new phenomena that already have a significant effect on society. As our
    current understanding of these phenomena is limited, studying them is critical to answering the questions their development
    raises. Indeed, social media exposes people to a previously impossible amount of social communication. Considering how easily
    information posted on social media can be manipulated, understanding the effect such exposure can have on people,
    especially young people, is crucial. The impact of online interactions on young people, as you mention, is particularly important
    as they are so receptive to outside influence. Social media have demonstrated their power to both harms and mend one’s
    mental health. Understanding how harmful or helpful they can be can even have legal ramifications, as is the case with online
    harassment or cyberbullying. As social media are increasing in their influence on one’s life, studying them should be a priority.`,
    `The far-reaching consequences of globalization can sometimes be very obscure. Just like preeminent technglobalization contributes to civilization as a whole but also inconveniences others. In terms of global trade, hpoor countries by increasing specialization, it expands access to information through trade, increases the patechnological and financial sectors. According to Oyekola (2018), “With globalization, more jobs can be creathe positive effects of globalization.Be that as it may, “economic activities carried out by humans such as agriculture, construction, fossil fuel bumining are causing harm not only to human life but also to the environment” (Rashid, 2021), and can be termglobalization in different countries. The extraction of non-renewable and renewable natural resources leadsenvironment.`,
    `Discipline refers to the values which are inculcated during childhood. Discipline as a value refers to organized and punctuality as a quality in a person. Discipline alone is enough for one to reach its goal. One can develop discipline in itself by working in an organized manner or systematically. It also helps to give clarity to mid as well, preventing any kind of chaos. One cannot attain its goal by being lazy. Discipline is working upon the things which are more important.Discipline is more important to be inculcated in students. With globalization and technology, one needs to be taught to be disciplined in every aspect of life. It's very important for students to schedule timetable for self in order to be effective in results both in curricular and co-curricular activities.`,

];
module.exports = {
    fifty, seventyfive, hundred , hundredfifty
};